# Generated by Django 5.2.7 on 2026-09-25 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_add_is_current_to_era'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eth_blockheight', models.BigIntegerField(blank=True, help_text='Block height at which this Motion was opened', null=True)),
            ],
            options={
                'db_table': 'motions',
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='motion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='conversations.motion'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['motion', 'created_at'], name='conversatio_motion__d1f81a_idx'),
        ),
    ]
