from django.urls import path
from . import views
from . import views_auth
from . import views_motions
from . import views_runner
from . import views_settings
from . import views_admin

urlpatterns = [
    path('motions/', views_motions.motions_page, name='motions'),
    path('motions/settings/', views_settings.settings_page, name='motion_settings'),
    path('motions/<slug:slug>/rules/', views_settings.rules_page, name='motion_rules'),
    path('motions/manifest.webmanifest', views_motions.app_manifest, name='motion_app_manifest'),
    path('motions/sw.js', views_motions.app_service_worker, name='motion_app_sw'),
    path('motions/icon-<int:size>.png', views_motions.app_icon, name='motion_app_icon'),
    path('motions/<slug:slug>/', views_motions.motions_page, name='motion'),
    path('motions/login/<str:code>/', views_auth.login_page, name='motion_login'),
    path('api/auth/challenge/', views_auth.api_challenge, name='auth_challenge'),
    path('api/auth/enroll/', views_auth.api_enroll, name='auth_enroll'),
    path('api/auth/me/', views_auth.api_me, name='auth_me'),
    path('api/auth/logout/', views_auth.api_logout, name='auth_logout'),
    path('api/auth/devices/', views_auth.api_devices, name='auth_devices'),
    path('api/auth/devices/<uuid:device_id>/revoke/', views_auth.api_device_revoke, name='auth_device_revoke'),
    path('api/auth/renew/', views_auth.api_renew, name='auth_renew'),
    path('api/attest/', views_auth.api_attest, name='api_attest'),
    path('api/motions/<slug:slug>/say/', views_auth.api_say, name='api_motion_say'),
    path('api/motions/<slug:slug>/rename/', views_auth.api_rename, name='api_motion_rename'),
    path('api/motions/', views_motions.api_motions, name='api_motions'),
    path('api/motions/pulse/', views_motions.api_pulse, name='api_motions_pulse'),
    path('api/settings/', views_settings.api_settings, name='api_settings'),
    path('api/auth/admin/', views_admin.api_admin, name='api_auth_admin'),
    path('api/motions/<slug:slug>/turns/', views_motions.api_motion_turns, name='api_motion_turns'),
    path('api/motions/<slug:slug>/sessions/', views_motions.api_motion_sessions, name='api_motion_sessions'),
    path('api/motions/<slug:slug>/steps/<str:step_id>/', views_motions.api_motion_step, name='api_motion_step'),
    path('api/motions/<slug:slug>/typing/', views_motions.api_typing, name='api_motion_typing'),
    path('api/motions/<slug:slug>/interrupt/', views_auth.api_interrupt, name='api_motion_interrupt'),
    path('api/motions/<slug:slug>/archive/', views_auth.api_archive, name='api_motion_archive'),
    path('api/motions/<slug:slug>/media/', views_auth.api_media, name='api_motion_media'),
    path('api/motions/<slug:slug>/stream/', views_runner.api_stream, name='api_motion_stream'),
    path('api/motions/<slug:slug>/quiet/', views_runner.api_quiet, name='api_motion_quiet'),
    path('api/motions/<slug:slug>/held/', views_runner.api_held, name='api_motion_held'),
    path('api/deploys/', views_runner.api_deploys, name='api_deploys'),
    path('api/servers/', views_runner.api_servers, name='api_servers'),
    path('motions/media/<str:sha256>.<str:ext>', views_motions.media_file, name='motion_media'),
    path('api/wikilinks/', views_motions.api_wikilinks, name='api_wikilinks'),
    path('api/mentions/<slug:name>/', views_motions.api_mentions, name='api_mentions'),
    path('api/notices/<slug:name>/', views_motions.api_notices, name='api_notices'),
    path('api/motions/new/', views_auth.api_new_motion, name='api_motions_new'),
    path('api/motions/recent/', views_motions.api_recent, name='api_motions_recent'),
    path('api/motions/live/', views_motions.api_motions_live, name='api_motions_live'),
    path('api/block/', views_motions.api_block, name='api_block'),
    path('api/search/', views_motions.api_search, name='api_search'),
    path('api/work/', views_motions.api_work, name='api_work'),
    path('memory_lane/', views.memory_lane, name='memory_lane'),
    path('spy/', views.stream, name='spy'),
    path('api/recent_messages/', views.recent_messages, name='recent_messages'),
    path('api/messages/', views.api_messages, name='api_messages'),
    path('api/all_messages/', views.all_messages, name='all_messages'),
    path('api/heap_metadata/', views.heap_metadata, name='heap_metadata'),
    path('api/heap_messages/<str:heap_id>/', views.heap_messages, name='heap_messages'),
    path('api/messages_since/<str:message_id>/', views.messages_since, name='messages_since'),
    path('api/ingest/', views.ingest, name='ingest'),
]
